INSERT INTO products (code, name, price) VALUES ('P001', 'Laptop', 799.99);
INSERT INTO products (code, name, price) VALUES ('P002', 'Smartphone', 599.49);
INSERT INTO products (code, name, price) VALUES ('P003', 'Tablet', 399.00);
INSERT INTO products (code, name, price) VALUES ('P004', 'Monitor', 199.99);
INSERT INTO products (code, name, price) VALUES ('P005', 'Keyboard', 49.99);
INSERT INTO products (code, name, price) VALUES ('P006', 'Mouse', 29.99);
INSERT INTO products (code, name, price) VALUES ('P007', 'Printer', 149.50);
INSERT INTO products (code, name, price) VALUES ('P008', 'Scanner', 129.75);
INSERT INTO products (code, name, price) VALUES ('P009', 'Webcam', 89.99);
INSERT INTO products (code, name, price) VALUES ('P010', 'Headphones', 79.95);
INSERT INTO products (code, name, price) VALUES ('P011', 'Speaker', 59.99);
INSERT INTO products (code, name, price) VALUES ('P012', 'External Hard Drive', 99.99);
INSERT INTO products (code, name, price) VALUES ('P013', 'USB Flash Drive', 19.99);
INSERT INTO products (code, name, price) VALUES ('P014', 'Router', 129.99);
INSERT INTO products (code, name, price) VALUES ('P015', 'Switch', 89.49);
INSERT INTO products (code, name, price) VALUES ('P016', 'Graphics Card', 499.99);
INSERT INTO products (code, name, price) VALUES ('P017', 'Motherboard', 249.99);
INSERT INTO products (code, name, price) VALUES ('P018', 'RAM 16GB', 79.99);
INSERT INTO products (code, name, price) VALUES ('P019', 'Power Supply', 109.99);
INSERT INTO products (code, name, price) VALUES ('P020', 'CPU Cooler', 59.99);
INSERT INTO products (code, name, price) VALUES ('P021', 'Gaming Chair', 199.99);
INSERT INTO products (code, name, price) VALUES ('P022', 'Desk Lamp', 39.99);
INSERT INTO products (code, name, price) VALUES ('P023', 'Microphone', 89.99);
INSERT INTO products (code, name, price) VALUES ('P024', 'Smartwatch', 149.99);
INSERT INTO products (code, name, price) VALUES ('P025', 'VR Headset', 299.99);